# Generated by Django 4.2.6 on 2023-10-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="please specify the title of the meeting",
                        max_length=255,
                        verbose_name="meeting title",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                (
                    "image",
                    models.ImageField(blank=True, height_field=100, null=True, upload_to="meetings/", width_field=100),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True, help_text="please provide a meeting link", null=True, verbose_name="meeting link"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="check the box if the meeting is active",
                        verbose_name="group is active",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="please enter a description of the meeting",
                        null=True,
                        verbose_name="group description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meeting",
            },
        ),
        migrations.CreateModel(
            name="MeetingAtention",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="MeetingOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("meeting_theme", models.CharField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeetingType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="please specify the title of the meeting",
                        max_length=255,
                        verbose_name="meeting title",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting type",
                "verbose_name_plural": "Meeting types",
            },
        ),
    ]
