# Generated by Django 4.2.6 on 2023-10-21 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="please specify the title of the meeting",
                        max_length=255,
                        verbose_name="meeting title",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting type",
                "verbose_name_plural": "Meeting types",
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="please specify the title of the meeting",
                        max_length=255,
                        verbose_name="meeting title",
                    ),
                ),
                ("image", models.ImageField(height_field=100, upload_to="meetings/", width_field=100)),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True, help_text="please provide a meeting link", null=True, verbose_name="meeting link"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="check the box if the meeting is active",
                        verbose_name="group is active",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="please enter a description of the meeting",
                        null=True,
                        verbose_name="group description",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        help_text="please chose lecturer for this meeting",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lecturer_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="lecturer",
                    ),
                ),
                (
                    "meeting_theme",
                    models.ForeignKey(
                        help_text="please chose theme for this meeting",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theme_meetings",
                        to="meetings.meetingtype",
                        verbose_name="lecturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meeting",
            },
        ),
    ]
