# Generated by Django 4.2.6 on 2023-10-22 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("meetings", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingoffer",
            name="lecturer",
            field=models.ForeignKey(
                help_text="please chose lecturer for this meeting",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lecturer_meetings",
                to="users.lecturer",
                verbose_name="lecturer",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="lecturer",
            field=models.ForeignKey(
                help_text="please chose lecturer for this meeting",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lecturer_meetings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="lecturer",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="meeting_theme",
            field=models.ForeignKey(
                help_text="please chose theme for this meeting",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="theme_meetings",
                to="meetings.meetingtype",
                verbose_name="lecturer",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="please chose learners for this meeting",
                related_name="user_meetings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="meeting learner",
            ),
        ),
    ]
