version: '3.9'


services:
  postgres:
    container_name: hack_db
    image: postgres:latest
    volumes:
      - postgres_data_database:/var/lib/postgresql/data/
    env_file:
      - ${PWD}/.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    expose:
      - ${DB_EXTERNAL_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data_database:
