version: '3.9'

services:
  db:
    container_name: postgresql
    image: postgres:15.3-alpine3.18
    restart: always
    hostname: postgresql
    env_file:
      - ${PWD}/.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 40

volumes:
  pgdata: