version: '3.9'


services:
  nginx:
    container_name: nginx
    image: nginx:1.25-alpine
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
    networks:
      - hacklife-balance-net

networks:
  hacklife-balance-net:
    driver: bridge