version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:1.25-alpine
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    container_name: postgresql
    image: postgres:15.3-alpine3.18
    restart: always
    hostname: postgresql
    env_file:
      - ${PWD}/.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 40

  backend:
    container_name: backend
    image: hack_backend
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - ${PWD}/:/app
    env_file: ${PWD}/.env
    command: sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn --workers=2 --threads=4 --worker-class=gthread --worker-connections=100 --worker-tmp-dir /dev/shm --bind 0.0.0.0:8000 backend.wsgi:application"
    volumes:
      - static:/app/django_static/
      - media:/app/django_media/
    depends_on:
      - db

volumes:
  pgdata:
  media:
  static:

