# Generated by Django 4.2.6 on 2023-10-22 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(help_text="full name of lecturer", verbose_name="full name")),
                (
                    "proffession",
                    models.CharField(help_text="the direction of the profession", verbose_name="proffession"),
                ),
                (
                    "descriptions",
                    models.TextField(help_text="please chose solution status", null=True, verbose_name="descriptions"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="account for interactions with platform",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lecturer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="account lecturer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("employee", "employee"), ("lecturer", "lecturer"), ("moderator", "moderator")],
                        help_text="Please chose role for this user",
                        verbose_name="user role name",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Please specify the user for this role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User role",
                "verbose_name_plural": "User roles",
            },
        ),
        migrations.CreateModel(
            name="LecturerMaterial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="title materia of lecturer matetial", verbose_name="title material"),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="please provide a material link", null=True, verbose_name="material link"
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        help_text="please chose which lecturer this matetial",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturer_materials",
                        to="users.lecturer",
                        verbose_name="lecturer",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(fields=("user", "role"), name="unique_user_role"),
        ),
    ]
