# Generated by Django 4.2.6 on 2023-10-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="raw_password",
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[("employee", "employee"), ("lecturer", "lecturer"), ("moderator", "moderator")],
                help_text="Please chose role for this user",
                verbose_name="user role name",
            ),
        ),
    ]
